config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'about', to: 'home#about'
  get 'trash', to: 'home#trash'

  resources :facts, except: [:index] do
    resources :versions, only: [:index]
  end
  resources :references, except: [:index] do
    resources :versions, only: [:index]
  end

  resources :versions, only: [:show] do
    member do
      post :restore
      get 'diff/:v2', to: :diff, as: :diff
    end
  end

  get 'categories/*category', to: 'categories#show'

end

app/models/fact.rb
class Fact < ActiveRecord::Base
  include WikiPage

  belongs_to :reference
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :references

  after_save :categorize
  after_save :reference

  def categorize
    categories.delete(*categories)
    categories_string.split(',').map(&:strip).each do |category_name|
      categories << Category.where(name: category_name).first_or_create
    end
  end

  def reference
    references.delete(*references)
    references_string.split(',').map(&:strip).each do |reference_key|
      references << Reference.find_by(key: reference_key)
    end
  end
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :set_fact, only: [:show, :edit, :update, :destroy, :versions, :restore_version]

  # GET /facts/1
  # GET /facts/1.json
  def show
  end

  # GET /facts/new
  def new
    @fact = Fact.new
  end

  # GET /facts/1/edit
  def edit
    @fact.version_description = nil
  end

  # POST /facts
  # POST /facts.json
  def create
    @fact = Fact.new(fact_params)

    respond_to do |format|
      if @fact.save
        format.html { redirect_to @fact, notice: 'Fact was successfully created.' }
        format.json { render :show, status: :created, location: @fact }
      else
        format.html { render :new }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facts/1
  # PATCH/PUT /facts/1.json
  def update
    respond_to do |format|
      if @fact.update(fact_params)
        @fact.categorize()
        format.html { redirect_to @fact, notice: 'Fact was successfully updated.' }
        format.json { render :show, status: :ok, location: @fact }
      else
        format.html { render :edit }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1
  # DELETE /facts/1.json
  def destroy
    @fact.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Fact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact
      @fact = Fact.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      version = PaperTrail::Version.where(event: 'destroy', item_type: 'Fact', item_id: params[:id]).first
      if version
        version_link = view_context.link_to("here", version_path(version))
        redirect_to root_url, notice: "Page was deleted. View the last version #{version_link}."
      else
        raise ActiveRecord::RecordNotFound if version.nil?
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fact_params
      params.require(:fact).permit(:summary, :content, :version_description)
    end

    def categories_param
      params.require(:fact).permit(:categories)
    end

    def references_param
      params.require(:fact).permit(:references)
    end
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_form.html.erb
<%= form_for(@fact) do |f| %>
    <%= f.text_area :title %>
    <%= f.text_area :content, class: 'large' %>
    <%= f.text_field :categories_string %>
    <%= f.text_field :references_string %>
    <%= f.text_area :version_description %>

    <div class="actions">
      <% unless @fact.new_record? %>
          <%= link_to 'Cancel', @fact, :class => 'small radius cancel button' %>
      <% end %>
      <%= f.submit 'Save', :class => 'small radius action button' %>
    </div>
<% end %>

app/views/facts/_show.html.erb
<div class="panel callout">
  <h5>
    <strong>Fact:</strong> <%= @fact.title %>
  </h5>
</div>

<%= markdownify(@fact.content) %>

<h4>References</h4>

<% @fact.references.each do |reference| %>
    <div class="panel">
      <h5>
        <%= link_to reference.title, reference %>
        <%= link_to '[open]', reference.url, { class: 'external', target: '_blank' } %>
      </h5>
      <%= reference.title %>
    </div>
<% end %>

app/views/facts/edit.html.erb
<div class="row">
  <div class="large-8 columns">
    <h3>Edit fact</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/facts/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Listing Facts</h1>

    <table>
      <thead>
        <tr>
          <th>Summary</th>
          <th>References</th>
          <th>Categories</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @facts.each do |fact| %>
            <tr>
              <td><%= fact.summary %></td>
              <td><%= fact.references_string %></td>
              <td><%= fact.categories_string %></td>
              <td><%= link_to 'Show', fact %></td>
              <td><%= link_to 'Edit', edit_fact_path(fact) %></td>
              <td><%= link_to 'Destroy', fact, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Fact', new_fact_path %>
  </div>
</div>

app/views/facts/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h3>New Fact</h3>

    <%= render 'form' %>
  </div>
</div>

app/views/facts/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="clearfix right">
      <span>Last updated <%= format_date @fact.updated_at %></span>
      &middot;
      <%= link_to 'Versions', fact_versions_path(@fact) %>
      &middot;
      <%= link_to 'Edit', edit_fact_path(@fact) %>
      &middot;
      <%= link_to 'Delete', @fact, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
  <div class="large-8 columns">

    <%= render 'facts/show' %>

    <h4>References</h4>

    <% @fact.references.each do |reference| %>
        <div class="panel">
          <h5>
            <%= link_to reference.title, reference %>
            <%= link_to '[open]', reference.url, { class: 'external', target: '_blank' } %>
          </h5>
          <%= reference.title %>
        </div>
    <% end %>

  </div>
  <div class="large-4 columns">
    <div class="panel">
      <h4>Categories</h4>
      <% @fact.categories.each do |category| %>
          <%= link_to category.name, "/categories/#{category.name}" %>
      <% end %>
    </div>
  </div>
</div>

app/views/facts/versions.html.erb
<div class="row">
  <div class="large-8 columns">
    <h3>Versions</h3>
    <table>
      <% @fact.versions.each do |v| %>
        <tr>
          <td><%= format_time v.created_at %></td>
          <td><%= link_to 'Restore', restore_version_fact_path %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>