config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'about', to: 'home#about'
  get 'trash', to: 'home#trash'

  resources :facts, except: [:index] do
    resources :versions, only: [:index]
  end
  resources :references, except: [:index] do
    resources :versions, only: [:index]
  end

  resources :versions, only: [:show] do
    member do
      post :restore
      get 'diff/:v2', to: :diff, as: :diff
    end
  end

  get 'categories/*category', to: 'categories#show'

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_resource, only: [:index]
  def index
    @versions = @resource.versions.
        select{ |v| v.event != 'create' }.
        sort_by{ |v| v.created_at }.
        reverse
  end

  def show
    @version = PaperTrail::Version.find(params[:id])
    @resource = @version.reify
    @fact = @resource if @version.item_type == 'Fact'
    @reference = @resource if @version.item_type == 'Reference'
  end

  def restore
    version = PaperTrail::Version.find(params[:id])
    resource = version.reify
    resource.version_description = "Restored v#{resource.id}"
    resource.save
    redirect_to resource
  end

  def diff
    @version1 = PaperTrail::Version.find(params[:id])
    @resource1 = @version1.reify

    if params[:v2] == 'CURRENT'
      @resource2 = @resource1.class.find(@resource1.id)
    else
      @version2 = PaperTrail::Version.find(params[:v2])
      @resource2 = @version2.reify
    end

    @title_diff = Diffy::Diff.new(@resource1.title, @resource2.title).to_s(:html).html_safe if @resource1.respond_to?(:title)
    @summary_diff = Diffy::Diff.new(@resource1.summary, @resource2.summary).to_s(:html).html_safe if @resource1.respond_to?(:summary)
    @content_diff = Diffy::Diff.new(@resource1.content, @resource2.content).to_s(:html).html_safe if @resource1.respond_to?(:content)
  end

private
  def set_resource
    @resource = Fact.find(params[:fact_id]) if params[:fact_id]
    @resource = Reference.find(params[:reference_id]) if params[:reference_id]
  end
end

app/views/versions/diff.html.erb
<div class="row">
  <div class="large-12 columns">
    <p>
      Diffing <%= link_to "v#{@resource1.version_number}", version_path(@version1) %> with
      <% if @version2.nil? %>
        <%= link_to 'CURRENT', @resource2 %>.
      <% else %>
        <%= link_to "v#{@resource2.version_number}", version_path(@version2) %>.
      <% end %>
  </div>
  <div class="large-8 columns">
    <% unless @title_diff.nil? %>
        <h3>Title</h3>
        <%= @title_diff %>
    <% end %>

    <% unless @summary_diff.nil? %>
        <h3>Summary</h3>
        <%= @summary_diff %>
    <% end %>

    <% unless @content_diff.nil? %>
        <h3>Content</h3>
        <%= @content_diff %>
    <% end %>
  </div>
  <div class="large-4 columns">

  </div>
</div>

app/views/versions/index.html.erb
<script>
    var version1, version2, diffButton;

    function diff() {
        var url = '/versions/' + version1 + '/diff/' + version2;
        window.location = url;
    }

    function validate() {
        if ($('input[name=version]:checked').length == 2) {
            diffButton.show();
        } else {
            diffButton.hide();
        }
    }

    function versionChecked() {
        version1 = $('input[name=version]:checked:last').val(),
                version2 = $('input[name=version]:checked:first').val();
        validate();
    }

    $(function() {
        diffButton = $('#diff');
        diffButton.click(diff);
        validate();
        $('input[name=version]').change(versionChecked);
    });
</script>

<div class="row">
  <div class="large-8 columns">
    <h3>Version History</h3>
    <p>Select any two versions to compare the diff</p>
    <table style="width: 100%;">
      <tr>
        <th></th>
        <th>Version</th>
        <th>Created</th>
        <th>Version Description</th>
        <th></th>
      </tr>
      <tr>
        <td><input type="checkbox" name="version" value="CURRENT" /></td>
        <td>CURRENT</td>
        <td><%= format_time @resource.updated_at %></td>
        <td><%= @resource.version_description %></td>
        <td><%= link_to 'View', @resource %></td>
      </tr>
      <% @versions.each do |v| %>
          <% reified_version = v.reify %>
          <tr>
            <td><input type="checkbox" name="version" value="<%= v.id %>" /></td>
            <td>v<%= reified_version.version_number %></td>
            <td><%= format_time v.created_at %></td>
            <td><%= reified_version.version_description %></td>
            <td><%= link_to 'View', version_path(v) %></td>
          </tr>
      <% end %>
    </table>
    <input type="button" id='diff' class="small button radius" href="#" value="Diff" />
  </div>
</div>

app/views/versions/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <p>Viewing version <%= @resource.version_number %>.
      <% if @resource.new_record? %>
          Resource deleted.
      <% else %>
          View the current version <%= link_to 'here', @resource %>.
      <% end %>
    </p>
  </div>
  <div class="large-8 columns">
    <% if @version.item_type == 'Fact' %>
        <%= render 'facts/show' %>
    <% end %>
    <% if @version.item_type == 'Reference' %>
        <%= render 'references/show' %>
    <% end %>
  </div>

  <div class="large-4 columns">
    <%= form_tag(restore_version_path(@version)) do %>
        <%= submit_tag 'Restore', :class => 'small button radius' %>
    <% end %>
  </div>
</div>