config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'about', to: 'home#about'
  get 'trash', to: 'home#trash'

  resources :facts, except: [:index] do
    resources :versions, only: [:index]
  end
  resources :references, except: [:index] do
    resources :versions, only: [:index]
  end

  resources :versions, only: [:show] do
    member do
      post :restore
      get 'diff/:v2', to: :diff, as: :diff
    end
  end

  get 'categories/*category', to: 'categories#show'

end

app/models/reference.rb
class Reference < ActiveRecord::Base
  include WikiPage

  has_and_belongs_to_many :facts
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references/1
  # GET /references/1.json
  def show
    @citations = @reference.facts
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
    @reference.version_description = nil
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      version = PaperTrail::Version.where(event: 'destroy', item_type: 'Reference', item_id: params[:id]).first
      if version
        version_link = view_context.link_to("here", version_path(version))
        redirect_to root_url, notice: "Page was deleted. View the last version #{version_link}."
      else
        raise ActiveRecord::RecordNotFound if version.nil?
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:key, :title, :author, :url, :summary, :version_description)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for(@reference) do |f| %>
    <%= f.text_field :title %>
    <%= f.text_area :content, class: 'large' %>
    <%= f.text_field :key %>
    <%= f.text_field :author %>
    <%= f.text_field :url %>
    <%= f.text_area :version_description %>
    <div class="actions">
      <% unless @reference.new_record? %>
          <%= link_to 'Cancel', @reference, :class => 'small radius cancel button' %>
      <% end %>
      <%= f.submit 'Save', :class => 'small radius action button' %>
    </div>
<% end %>

app/views/references/_show.html.erb
<h3><%= @reference.title %></h3>

<p><%= @reference.content %></p>

<p>
  <strong>Key:</strong>
  <%= @reference.key %>
</p>

<p style="word-wrap:break-word;">
  <%= link_to @reference.url %>
</p>

app/views/references/edit.html.erb
<div class="row">
  <div class="large-8 columns">
    <h3>Edit reference</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/references/index.html.erb
<div class="row">
  <div class="large-12 columns">

    <h1>Listing References</h1>

    <table>
      <thead>
        <tr>
          <th>Key</th>
          <th>Title</th>
          <th>Author</th>
          <th>Url</th>
          <th>Summary</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @references.each do |reference| %>
          <tr>
            <td><%= reference.key %></td>
            <td><%= reference.title %></td>
            <td><%= reference.author %></td>
            <td><%= reference.url %></td>
            <td><%= reference.summary %></td>
            <td><%= link_to 'Show', reference %></td>
            <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
            <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Reference', new_reference_path %>
  </div>
</div>

app/views/references/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>New Reference</h1>

    <%= render 'form' %>

    <%= link_to 'Back', references_path %>
  </div>
</div>

app/views/references/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="clearfix right">
      <span>Last updated <%= format_date @reference.updated_at %></span>
      &middot;
      <%= link_to 'Versions', reference_versions_path(@reference) %>
      &middot;
      <%= link_to 'Edit', edit_reference_path(@reference) %>
      &middot;
      <%= link_to 'Delete', @fact, method: :delete, data: {confirm: 'Are you sure?'} %>
    </div>
  </div>
  <div class="large-8 columns">
    <%= render 'references/show' %>
  </div>
  <div class="large-4 columns" %>
    <div class="panel">
      <h3>Citations</h3>
      <ul class="square">
        <% @citations.each do |fact| %>
            <li>
              <strong>Fact:</strong> <%= link_to fact.title, fact %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>